{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: Secret
metadata:
  name: cd-token
  namespace: {{ template "web.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
{{- end }}