{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring
  labels:
    {{- include "web.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: {{ template "web.namespace" . }}
{{- end }}