{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring
  labels:
    {{- include "web.labels" . | nindent 4 }}
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}