apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ template "web.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  file: |
{{- range $key, $val := .Values.data }}
{{ $key | quote | indent 4}}: {{ $val | quote }}
{{- end}}