{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd
  namespace: {{ template "web.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cd
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: {{ template "web.namespace" . }}
{{- end }}