{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
{{- end }}