apiVersion: v1
kind: Service
metadata:
  name: nginx-stub-status
  labels:
    app: nginx-stub-status
spec:
  selector:
    app: nginx-stub-status
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics