apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: homework
spec:
  accessModes:    
    - ReadWriteOnce
  storageClassName: "custom"
  volumeMode: Filesystem  
  resources:    
    requests:      
      storage: 1Gi